### ISSUE TITLE
Cache + GAE

### ISSUE THREAD

**Issue by GoogleCodeExporter** [degloba/svndegloba#25]
```
http://www.ehcache.org/generated/2.9.0/html/ehc-all/index.html#page/Ehcache_Docu
mentation_Set/co-gae_about_google_app_and_ehcache.html

```

Original issue reported on code.google.com by `degl...@degloba.com` on 5 Mar 2015 at 11:27

**Comment by degloba** [comment]
http://www.ehcache.org/generated/2.9.0/html/ehc-all/index.html#page/Ehcache_Documentation_Set%2Fto-gae_using_ehcache_with_the_google_app_engine.html%23
