### ISSUE TITLE
google-api-java-client OAuth 2.0 (Github)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [degloba/svndegloba#28]
https://github.com/google/google-api-java-client

Original issue reported on code.google.com by `degl...@degloba.com` on 9 Mar 2015 at 1:33

**Comment by degloba** [comment]
https://developers.google.com/api-client-library/java/google-api-java-client/app-engine

**Comment by degloba** [comment]
https://cloud.google.com/appengine/docs/java/oauth/
